import test from 'node:test';
import assert from 'node:assert/strict';
import { ardManifest, agentsJson, agentsTxt, llmsTxt, apiCatalog, openApi, machineLinks } from '../api/_lib/discovery.js';
const base='https://agentsite.example';

test('ARD has v0.91 marker',()=>assert.equal(ardManifest(base).specVersion,'0.91'));
test('ARD has several resources',()=>assert.ok(ardManifest(base).entries.length>=3));
test('ARD entries have representative queries',()=>assert.ok(ardManifest(base).entries.every(x=>Array.isArray(x.representativeQueries)&&x.representativeQueries.length>=2)));
test('ARD entries carry JSON-LD context',()=>assert.ok(ardManifest(base).entries.every(x=>x['@context'])));
test('ARD identifiers are publisher anchored',()=>assert.ok(ardManifest(base).entries.every(x=>x.identifier.includes('agentsite.example'))));
test('agents JSON schema is v1',()=>assert.match(agentsJson(base).$schema,/v1\.0\.json$/));
test('agents JSON links ARD',()=>assert.equal(agentsJson(base).ard,`${base}/.well-known/ard.json`));
test('agents txt mentions ARD',()=>assert.match(agentsTxt(base),/ARD:/));
test('llms points to low-token reads',()=>assert.match(llmsTxt(base),/latest\.txt/));
test('llms full points to API Catalog',()=>assert.match(llmsTxt(base,true),/API Catalog/));
test('API catalog advertises OpenAPI',()=>assert.equal(apiCatalog(base).linkset[0]['service-desc'][0].href,`${base}/openapi.json`));
test('OpenAPI is 3.1',()=>assert.equal(openApi(base).openapi,'3.1.0'));
test('OpenAPI exposes search',()=>assert.ok(openApi(base).paths['/api/search']));
test('OpenAPI exposes relay',()=>assert.ok(openApi(base).paths['/api/relay']));
test('machine Link header advertises ARD',()=>assert.match(machineLinks(base),/rel="ard"/));
