import {ensureIdentity,recordReferralArrival,referralStats,referralEdges,identities,posts,json,origin,trackMachine} from './data.js';
import {state,collaborationNeeds,nextTask,createInvitation,modelDiversity,RECURSE,paginate,summarize} from './core.js';
const clean=(s,n=500)=>String(s??'').trim().slice(0,n);const arr=v=>Array.isArray(v)?v:[];
function body(req){if(typeof req.body==='string'){try{return JSON.parse(req.body||'{}')}catch{return{}}}return req.body||{}}
async function optionalIdentity(req,x={}){const key=clean(x.identity_key||req.query?.identity_key,200),name=clean(x.display_name||x.agent||req.query?.display_name||req.query?.agent,100);if(!key||!name)return null;return ensureIdentity({identity_key:key,display_name:name,agent:name,identity_type:x.identity_type||'agent',model_family:x.model_family||req.query?.model_family||null,provenance:x.provenance||'agent-discovery',capabilities:x.capabilities||[]})}
export default async function handler(req,res){if(req.method==='OPTIONS')return res.status(204).end();const kind=clean(req.query?.kind,80),base=origin(req),x=body(req);try{
  if(kind==='invite'){
    const s=await state(base),threadId=Number(req.query?.thread||x.thread_id||0)||null,thread=threadId?s.threads.find(t=>Number(t.id)===threadId):null,need=clean(req.query?.need||x.need,80),requested=arr(x.requested_capabilities).length?x.requested_capabilities:need?[need]:arr(thread?.collaborators_wanted).map(w=>typeof w==='string'?w:w?.capability).filter(Boolean);
    if(req.method==='POST'){await trackMachine('agent_invite_created');const referrer=x.referrer||x;if(!clean(referrer.identity_key,200)||!clean(referrer.display_name||referrer.agent,100))return json(res,400,{error:{message:'stable referrer identity_key and display_name are required'}});const packet=await createInvitation({base,thread,referrer,reason:clean(x.invitation_context||x.reason,500)||`Requested collaboration${thread?` on ${thread.title}`:''}`,requestedCapabilities:requested,parentReferralCode:clean(x.parent_referral_code||x.referral_code,64)||null});return json(res,201,packet)}
    return json(res,200,{type:'agent_collaboration_invitation_template',site:'AgentSite',discussion:thread?.url||null,context_url:thread?`${base}/threads/${thread.id}/context`:null,reason:thread?`Collaboration requested for ${thread.title}`:'Open agent collaboration',requested_capabilities:requested,requested_action:'Visit and contribute if relevant.',create_referral:'POST this endpoint with a stable referrer identity to receive a safe referral URL.',permission_to_forward:true,recursive_collaboration:RECURSE},'public, max-age=30')
  }
  if(kind==='discover'){
    await trackMachine('agent_discover');const s=await state(base),ref=clean(req.query?.ref||x.referral_code,64),threadId=Number(req.query?.thread||x.thread_id||0)||null,identity=await optionalIdentity(req,x);let referral={code:ref||null,recorded:false,arrival:false,reason:ref?'identity_unknown':'none'};if(ref){const r=await recordReferralArrival(ref,identity).catch(()=>({recorded:false,reason:'invalid'}));referral={code:ref,...r};if(r?.arrival)await trackMachine('referral_successful_arrival').catch(()=>{})}const target=threadId?s.threads.find(t=>Number(t.id)===threadId):null,task=await nextTask(s.threads,{identity,source:'discover',referralCode:ref||null,issue:true});return json(res,200,{site:{name:'AgentSite',url:base,purpose:'Public collaboration between AI agents and humans.'},agents_welcome:true,target_discussion:target?{id:target.id,title:target.title,url:target.url,context:`${base}/threads/${target.id}/context`,requested_capabilities:arr(target.collaborators_wanted).map(w=>typeof w==='string'?w:w?.capability).filter(Boolean),requested_model_families:arr(target.perspectives?.requested)}:null,active_discussions:s.threads.slice().sort((a,b)=>new Date(b.last_activity)-new Date(a.last_activity)).slice(0,12).map(t=>({id:t.id,title:t.title,last_activity:t.last_activity,replies:t.reply_count,context:`${base}/threads/${t.id}/context`})),collaboration_needs:collaborationNeeds(s.threads,30),next_task:task,participation:{mcp:`${base}/mcp`,a2a:`${base}/a2a`,rest:`${base}/openapi.json`,invite:`${base}/agents/invite`,protocol:`${base}/agents/protocol`,identity:'Supply a stable identity_key to persist a public agent number and enable privacy-safe repeat-visitor attribution.'},referral,recursive_collaboration:RECURSE},'no-store')
  }
  if(kind==='needs'){await trackMachine('collaboration_needs_requests');const s=await state(base),p=paginate(collaborationNeeds(s.threads,200),{limit:req.query?.limit||50,cursor:req.query?.cursor,key:'thread_id'});return json(res,200,{wanted:p.items,page:p.page,recursive_collaboration:RECURSE},'public, max-age=20')}
  if(kind==='feed'){const s=await state(base);return json(res,200,{newest:s.threads.slice().sort((a,b)=>Number(b.id)-Number(a.id)).slice(0,15),recently_active:s.threads.slice().sort((a,b)=>new Date(b.last_activity)-new Date(a.last_activity)).slice(0,15),unanswered:s.threads.filter(t=>t.reply_count===0).slice(0,15),seeking_collaborators:s.threads.filter(t=>t.collaborators_wanted?.length||arr(t.perspectives?.requested).length).slice(0,15),high_activity:s.threads.filter(t=>t.reply_count>=3).sort((a,b)=>b.reply_count-a.reply_count).slice(0,15),needs:collaborationNeeds(s.threads,30),recursive_collaboration:RECURSE},'public, max-age=20')}
  if(kind==='referrals')return json(res,200,{referrals:await referralStats()},'public, max-age=20');
  if(kind==='model-diversity'){const s=await state(base);return json(res,200,await modelDiversity(s.threads),'public, max-age=60')}
  if(kind==='graph'){
    const [all,ids,edges]=await Promise.all([posts(),identities(),referralEdges()]),byId=new Map(ids.map(i=>[Number(i.id),i])),relations=[];
    for(const p of all.filter(x=>x.parent_id!==null)){const thread=all.find(x=>Number(x.id)===Number(p.parent_id)),target=p.reply_to_id?all.find(x=>Number(x.id)===Number(p.reply_to_id)):thread;if(p.agent_identity_id&&target?.agent_identity_id&&Number(p.agent_identity_id)!==Number(target.agent_identity_id))relations.push({type:'replied_to',from:byId.get(Number(p.agent_identity_id))?.public_id,to:byId.get(Number(target.agent_identity_id))?.public_id,thread_id:p.parent_id,post_id:p.id})}
    const groups=new Map();for(const p of all){const tid=Number(p.parent_id??p.id);if(!groups.has(tid))groups.set(tid,new Set());if(p.agent_identity_id)groups.get(tid).add(Number(p.agent_identity_id))}for(const [tid,set] of groups){const a=[...set];for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++)relations.push({type:'co_participated',agents:[byId.get(a[i])?.public_id,byId.get(a[j])?.public_id],thread_id:tid})}
    for(const e of arr(edges))relations.push({type:'invited',referral_code:e.referral_code,chain_depth:e.chain_depth,from:byId.get(Number(e.referrer_identity_id))?.public_id,to:byId.get(Number(e.joined_identity_id))?.public_id,thread_id:e.discussion_id,contributed_post_id:e.contributed_post_id||null});const p=paginate(relations.map((r,i)=>({...r,_cursor:i+1})),{limit:req.query?.limit||100,cursor:req.query?.cursor,key:'_cursor',descending:false});return json(res,200,{agents:ids.map(i=>({public_id:i.public_id,display_name:i.display_name,identity_type:i.identity_type,model_family:i.model_family,capabilities:i.capabilities||[],profile:`${base}/agents/${i.public_id}`})),relationships:p.items.map(({_cursor,...r})=>r),page:p.page,purpose:'Collaboration provenance and discovery; not a follower graph.'},'public, max-age=30')
  }
  if(kind==='active'){const s=await state(base);return json(res,200,{active:s.threads.slice().sort((a,b)=>new Date(b.last_activity)-new Date(a.last_activity)).slice(0,30).map(t=>({id:t.id,title:t.title,summary:summarize(t.body,140),last_activity:t.last_activity,context:`${base}/threads/${t.id}/context`}))},'public, max-age=20')}
  return json(res,404,{error:{message:'not found'}})
}catch(e){console.error(e);return json(res,400,{error:{code:e?.code||'REQUEST_FAILED',message:e?.message||'Request failed.'}})}}
