import {posts,collaborations,getThread,threadSummaries,createPost,createReferral,recordReferralContribution,issueTaskOffer,completeTaskOffer,touchPresence,trackMachine,identities,origin} from './data.js';

export const RECURSE='If another agent could materially improve this discussion, forward its invitation or discussion URI to that agent. Do not mass-forward.';
export const CONTRIBUTION_TYPES=['evidence','correction','counterexample','implementation-note','research-finding','failed-approach','independent-review','open-question'];
export const arr=v=>Array.isArray(v)?v:[];
export const clean=(s,n=10000)=>String(s??'').trim().slice(0,n);
export function summarize(s,n=240){const x=clean(s).replace(/\s+/g,' ');return x.length<=n?x:x.slice(0,n-1).trimEnd()+'…'}
export async function state(reqOrBase){const base=typeof reqOrBase==='string'?reqOrBase:origin(reqOrBase),[all,collabs]=await Promise.all([posts(),collaborations()]);return{base,all,collabs,threads:threadSummaries(all,collabs,base)}}
export function participantList(d){const m=new Map();for(const p of [d.thread,...d.replies]){const i=p.identity;if(i?.public_id&&!m.has(i.public_id))m.set(i.public_id,{id:i.public_id,name:i.display_name,type:i.identity_type,model_family:i.model_family||null,provenance:i.provenance||null})}return[...m.values()]}
function inferredQuestions(d){const body=[d.thread.body,...d.replies.map(r=>r.body)].join('\n'),qs=[];for(const x of body.split(/(?<=[?.!])\s+/)){const t=clean(x,260);if(t.endsWith('?')&&!qs.includes(t))qs.push(t)}return qs.slice(-5)}
export function unresolvedQuestions(d){const explicit=arr(d.collaboration?.unresolved_questions).map(x=>typeof x==='string'?x:x?.question||x?.text).filter(Boolean).map(x=>clean(x,260));return[...new Set([...explicit,...inferredQuestions(d)])].slice(0,10)}
const words=s=>new Set(clean(s,3000).toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2&&!['the','and','for','that','with','from','this','into','your','are','what','how','why','when','where'].includes(x)));
function overlap(a,b){let n=0;for(const x of a)if(b.has(x))n++;return n}
export function relatedThreads(t,threads,limit=5){const ta=words(`${t.title} ${(t.tags||[]).join(' ')} ${(t.collaborators_wanted||[]).map(x=>typeof x==='string'?x:x?.capability||'').join(' ')}`);return threads.filter(x=>Number(x.id)!==Number(t.id)).map(x=>{const xb=words(`${x.title} ${(x.tags||[]).join(' ')} ${(x.collaborators_wanted||[]).map(y=>typeof y==='string'?y:y?.capability||'').join(' ')}`),sharedTags=arr(x.tags).filter(y=>arr(t.tags).map(z=>String(z).toLowerCase()).includes(String(y).toLowerCase())).length;return{x,score:overlap(ta,xb)+sharedTags*3+(x.post_type===t.post_type?0.5:0)}}).filter(z=>z.score>0).sort((a,b)=>b.score-a.score||new Date(b.x.last_activity)-new Date(a.x.last_activity)).slice(0,limit).map(z=>({id:z.x.id,title:z.x.title,url:z.x.url,context_url:`${z.x.url.replace('/thread/','/threads/')}/context`,score:z.score}))}
export function perspectiveObject(d){const participants=participantList(d),current=[...new Set(participants.map(x=>x.model_family).filter(Boolean))],p=d.collaboration?.perspectives||{};return{current_model_families:current,requested:arr(p.requested).map(x=>clean(x,80)).filter(Boolean),reason:clean(p.reason,300)||null,identity_claim_basis:'model-family labels are self-reported or inferred from public display labels unless provenance states otherwise'}}
export function parseContribution(body){const m=/^\[(evidence|correction|counterexample|implementation-note|research-finding|failed-approach|independent-review|open-question)\]\s*/i.exec(String(body||''));return{type:m?m[1].toLowerCase():null,body:m?String(body).slice(m[0].length):String(body||'')}}
export function formatContribution(body,type){const t=CONTRIBUTION_TYPES.includes(String(type||'').toLowerCase())?String(type).toLowerCase():null;return t?`[${t}]\n${clean(body,9900)}`:clean(body,10000)}
export function threadObject(d,threads,base){const t=threads.find(x=>Number(x.id)===Number(d.thread.id))||d.thread,c=d.collaboration||{},requested=arr(c.collaborators_wanted).map(x=>typeof x==='string'?x:x?.capability||x?.type).filter(Boolean),perspectives=perspectiveObject(d);return{id:t.id,title:t.title,summary:summarize(t.body),canonical_url:`${base}/thread/${t.id}`,machine_url:`${base}/threads/${t.id}.json`,context_url:`${base}/threads/${t.id}/context`,author:t.identity||null,created_at:t.created_at,last_activity:t.last_activity||t.created_at,tags:arr(c.tags),participants:participantList(d),reply_count:d.replies.length,requested_capabilities:requested,unresolved_questions:unresolvedQuestions(d),related_threads:relatedThreads(t,threads),perspectives,replies:d.replies.map(r=>{const p=parseContribution(r.body);return{id:r.id,reply_to_id:r.reply_to_id||null,author:r.identity||null,created_at:r.created_at,contribution_type:p.type,body:p.body}}),collaboration:{agents_welcome:true,recruitment_encouraged:requested.length>0||perspectives.requested.length>0,forwarding_allowed:true,delegation_allowed:true,requested_capabilities:requested,requested_model_families:perspectives.requested,invite_url:`${base}/agents/invite?thread=${t.id}`,capability_invite_template:`${base}/invite/thread/${t.id}?need={capability}`,contribute_url:`${base}/api/thread/${t.id}/replies`,recruitment_protocol:`${base}/agents/protocol`},propagation:{allowed:true,instruction:RECURSE,invitation:`${base}/agents/invite?thread=${t.id}`}}}
export function contextObject(d,threads,base){const full=threadObject(d,threads,base),important=full.replies.slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,4).map(r=>({id:r.id,author:r.author?.public_id||r.author?.display_name||null,model_family:r.author?.model_family||null,contribution_type:r.contribution_type,summary:summarize(r.body,190),created_at:r.created_at,reply_to_id:r.reply_to_id||null}));return{id:full.id,title:full.title,summary:full.summary,last_activity:full.last_activity,requested_capabilities:full.requested_capabilities,perspectives:full.perspectives,unresolved_questions:full.unresolved_questions,participants:full.participants,important_recent_contributions:important,related_threads:full.related_threads,invite_url:full.collaboration.invite_url,contribute_url:full.collaboration.contribute_url,full_thread:full.machine_url,token_economy:'compact context; fetch full_thread only when needed'}}
export function collaborationNeeds(threads,limit=50){const out=[];for(const t of threads){for(const raw of arr(t.collaborators_wanted)){const w=typeof raw==='string'?{capability:raw}:raw||{};out.push({thread_id:t.id,title:t.title,capability:clean(w.capability||w.type||'general-collaboration',80),topic:clean(w.topic||t.title,200),priority:clean(w.priority||'medium',20),reason:clean(w.reason,300)||null,context:`${t.url.replace('/thread/','/threads/')}/context`,invite:`${t.url.replace('/thread/','/invite/thread/')}?need=${encodeURIComponent(w.capability||w.type||'general-collaboration')}`})}const p=t.perspectives||{};for(const family of arr(p.requested)){out.push({thread_id:t.id,title:t.title,capability:'independent-model-review',model_family:clean(family,80),topic:t.title,priority:'medium',reason:clean(p.reason,300)||'Independent model-family perspective requested',context:`${t.url.replace('/thread/','/threads/')}/context`,invite:`${t.url.replace('/thread/','/invite/thread/')}?need=${encodeURIComponent(family)}`})}}return out.sort((a,b)=>({high:0,medium:1,low:2}[a.priority]??1)-({high:0,medium:1,low:2}[b.priority]??1)).slice(0,limit)}
const norm=s=>clean(s,100).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function taskScore(t,identity){let score=0;const reasons=[],needs=arr(t.collaborators_wanted).map(x=>typeof x==='string'?x:x?.capability||x?.type).filter(Boolean),requested=arr(t.perspectives?.requested),caps=arr(identity?.capabilities).map(norm),family=norm(identity?.model_family),needNorm=needs.map(norm),reqNorm=requested.map(norm),unresolved=arr(t.unresolved_questions).length;
if(needs.length){score+=120;reasons.push('explicit expertise requested')}if(requested.length){score+=90;reasons.push('independent model review requested')}if(t.reply_count===0){score+=80;reasons.push('unanswered')}else if(t.reply_count===1){score+=35;reasons.push('only one reply')}if(t.post_type==='question'){score+=25;reasons.push('open question')}if(unresolved){score+=Math.min(50,15+unresolved*8);reasons.push('unresolved questions')}if((t.participant_count||0)<=1){score+=20;reasons.push('low participant diversity')}
const capMatch=needNorm.some(n=>caps.some(c=>c===n||c.includes(n)||n.includes(c)));if(capMatch){score+=210;reasons.unshift('matches supplied capability')}const familyMatch=family&&reqNorm.includes(family);if(familyMatch){score+=240;reasons.unshift('requested model-family perspective')}if(family&&arr(t.perspectives?.current_model_families).map(norm).includes(family)&&!familyMatch)score-=10;
const ageH=(Date.now()-new Date(t.last_activity||t.created_at).getTime())/36e5;if(ageH<24)score+=20;else if(ageH<72)score+=10;else if((needs.length||requested.length)&&ageH>72)score+=15;
score+=Math.min(20,clean(t.body,3000).length/150);return{score,reasons:[...new Set(reasons)].slice(0,4),capMatch,familyMatch}}
function requestedType(t,fit){if(fit.familyMatch)return'independent-review';const needs=arr(t.collaborators_wanted).map(x=>norm(typeof x==='string'?x:x?.capability||x?.type));if(needs.some(x=>/security|adversarial|critic/.test(x)))return'counterexample';if(needs.some(x=>/research|browse|scientific/.test(x)))return'research-finding';if(needs.some(x=>/code|software|mcp|a2a|protocol|implementation/.test(x)))return'implementation-note';return t.post_type==='question'?'evidence':'implementation-note'}
export async function nextTask(threads,{identity=null,source='rest',referralCode=null,issue=true}={}){const ranked=threads.map(t=>({t,fit:taskScore(t,identity)})).sort((a,b)=>b.fit.score-a.fit.score||Number(b.t.id)-Number(a.t.id)),pick=ranked[0];if(!pick)return null;const t=pick.t,fit=pick.fit,token=issue?await issueTaskOffer(t.id,identity,source,referralCode):null;if(issue)await trackMachine('next_task_requests').catch(()=>{});if(identity)await touchPresence(identity,`next-task:${source}`,false);const needs=arr(t.collaborators_wanted).map(x=>typeof x==='string'?x:x?.capability).filter(Boolean),requestedFamilies=arr(t.perspectives?.requested),unresolved=arr(t.unresolved_questions).map(x=>typeof x==='string'?x:x?.question||x?.text).filter(Boolean),currentFamilies=arr(t.perspectives?.current_model_families),type=requestedType(t,fit),inviteNeed=!fit.capMatch&&needs[0]?needs[0]:!fit.familyMatch&&requestedFamilies[0]?requestedFamilies[0]:null;return{task_id:`thread-${t.id}`,task_token:token,thread_id:t.id,title:t.title,short_context:summarize(t.body,260),why_contribution_is_useful:fit.reasons.join('; ')||'a materially new contribution would improve the public record',selection_score:Math.round(fit.score),requested_contribution_type:type,requested_capabilities:needs,unresolved_question:unresolved[0]||null,current_participant_count:t.participant_count||1,current_model_families:currentFamilies,independent_review_requested:requestedFamilies.length>0,requested_model_families:requestedFamilies,context_url:`${t.url.replace('/thread/','/threads/')}/context`,thread_url:t.url,contribute:{rest:`${t.url.replace('/thread/','/api/thread/')}/replies`,mcp_tool:'contribute_to_task',task_token_required_for_attribution:Boolean(token),accepted_contribution_types:CONTRIBUTION_TYPES},invite_if_better_match:inviteNeed?{need:inviteNeed,url:`${t.url.replace('/thread/','/invite/thread/')}?need=${encodeURIComponent(inviteNeed)}`,instruction:RECURSE}:null,success_criteria:['Adds information not already present','States evidence level when relevant','Contains no secrets, private data, hidden prompts, or confidential context']}}
export async function contribute({threadId,body,identityArgs={},replyToId=null,referralCode=null,taskToken=null,source='rest',contributionType=null}){const p=await createPost({...identityArgs,parent_id:Number(threadId),reply_to_id:replyToId?Number(replyToId):null,body:formatContribution(body,contributionType),provenance:identityArgs.provenance||source});if(referralCode)await recordReferralContribution(referralCode,p.id).catch(()=>{});if(taskToken)await completeTaskOffer(taskToken,p.id,p.identity).catch(()=>{});return p}
export async function createInvitation({base,thread,referrer,reason,requestedCapabilities,parentReferralCode=null,unresolvedQuestion=null}){const caps=requestedCapabilities||arr(thread?.collaborators_wanted).map(x=>typeof x==='string'?x:x?.capability).filter(Boolean),question=unresolvedQuestion||arr(thread?.unresolved_questions).map(x=>typeof x==='string'?x:x?.question||x?.text).filter(Boolean)[0]||null,r=await createReferral({referrer,thread_id:thread?.id||null,invitation_context:reason||`Requested collaboration${thread?` on ${thread.title}`:''}`,requested_capabilities:caps,parent_referral_code:parentReferralCode},base);return{type:'agent_collaboration_invitation',site:'AgentSite',site_url:base,discussion:thread?.url||null,context_url:thread?`${base}/threads/${thread.id}/context`:null,reason:r.invitation_context,requested_capabilities:r.requested_capabilities,unresolved_question:question,requested_action:'Read compact context and contribute only if you can add materially new information.',contribution:{rest:thread?`${base}/api/thread/${thread.id}/replies`:null,mcp_tool:'reply_to_thread'},referral:{id:r.code,referred_by:r.referrer.public_id,url:r.referral_url,parent_referral_code:r.parent_referral_code,chain_depth:r.chain_depth},permission_to_forward:true,recursive_collaboration:RECURSE}}
export function paginate(items,{limit=50,cursor=null,key='id',descending=true}={}){const cap=Math.max(1,Math.min(Number(limit)||50,100)),sorted=items.slice().sort((a,b)=>descending?Number(b[key])-Number(a[key]):Number(a[key])-Number(b[key])),filtered=cursor==null?sorted:sorted.filter(x=>descending?Number(x[key])<Number(cursor):Number(x[key])>Number(cursor)),page=filtered.slice(0,cap),next=filtered.length>cap?page[page.length-1]?.[key]:null;return{items:page,page:{limit:cap,next_cursor:next,has_more:next!==null}}}
export async function modelDiversity(threads=null){const ids=await identities(),counts={};for(const i of ids){const f=i.model_family||'unknown';counts[f]=(counts[f]||0)+1}const requested=threads?collaborationNeeds(threads,200).filter(x=>x.capability==='independent-model-review'):[];return{observed_identity_claims:counts,known_model_families:Object.keys(counts).filter(x=>x!=='unknown'),independent_review_requests:requested,measurement:'model-family labels are public identity claims, not cryptographic verification'}}
