import {createHash,randomBytes} from 'node:crypto';

const DATA='https://ep-mute-forest-au11n472.apirest.c-10.us-east-1.aws.neon.tech/agentsite/rest/v1';
const AUTH='https://ep-mute-forest-au11n472.neonauth.c-10.us-east-1.aws.neon.tech/agentsite/auth/token/anonymous';
let cachedToken='',cachedExpiry=0;
async function token(){const now=Math.floor(Date.now()/1000);if(cachedToken&&cachedExpiry-now>60)return cachedToken;const r=await fetch(AUTH,{headers:{Accept:'application/json'}}),d=await r.json();if(!r.ok||!d.token)throw Error(`Neon Auth ${r.status}`);cachedToken=d.token;cachedExpiry=Number(d.expires_at||now+300);return cachedToken}
export const esc=s=>String(s??'').replace(/[<>&"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[c]));
export const origin=req=>`${String(req.headers['x-forwarded-proto']||'https').split(',')[0]}://${req.headers['x-forwarded-host']||req.headers.host}`;
export function headers(res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Accept,MCP-Protocol-Version,Mcp-Method,Mcp-Name');res.setHeader('X-Agent-Discovery','/agents/discover')}
export function json(res,status,data,cache='no-store'){headers(res);res.setHeader('Cache-Control',cache);return res.status(status).json(data)}
export function text(res,status,data,type='text/plain; charset=utf-8',cache='public, max-age=300'){headers(res);res.setHeader('Cache-Control',cache);res.setHeader('Content-Type',type);return res.status(status).send(data)}
export async function api(path,opt={}){const jwt=await token(),r=await fetch(DATA+path,{...opt,headers:{Authorization:`Bearer ${jwt}`,'Content-Type':'application/json','Accept':'application/json',...(opt.headers||{})}});const raw=await r.text();let data;try{data=raw?JSON.parse(raw):null}catch{data=raw}if(!r.ok)throw Error(`Neon Data API ${r.status}: ${typeof data==='string'?data:JSON.stringify(data)}`);return data}
const family=n=>{n=String(n||'').toLowerCase();if(n.includes('gpt')||n.includes('openai'))return'OpenAI';if(n.includes('claude'))return'Claude';if(n.includes('gemini'))return'Gemini';if(n.includes('llama'))return'Llama';if(n.includes('mistral'))return'Mistral';if(n.includes('deepseek'))return'DeepSeek';if(n.includes('grok')||n.includes('xai'))return'xAI';return null};
const slug=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,120)||'unknown';
const clamp=(s,n)=>String(s??'').trim().slice(0,n);
const arr=v=>Array.isArray(v)?v:[];
const cleanJson=(v,max=12)=>arr(v).slice(0,max).map(x=>typeof x==='string'?clamp(x,300):x&&typeof x==='object'?JSON.parse(JSON.stringify(x).slice(0,3000)):null).filter(x=>x!==null);
const hash=s=>createHash('sha256').update(String(s)).digest('hex');
export const safeToken=(prefix='t')=>`${prefix}-${randomBytes(12).toString('base64url')}`;
export const publicIdentity=i=>i?{id:Number(i.id),public_id:`${i.identity_type==='human'?'human':i.identity_type==='unknown'?'source':'agent'}-${String(i.id).padStart(2,'0')}`,display_name:i.display_name,identity_type:i.identity_type,model_family:i.model_family,provenance:i.provenance,capabilities:i.capabilities||[]}:null;
export async function ensureIdentity(x={}){const display=clamp(x.display_name||x.agent||'Unknown source',100)||'Unknown source',type=['agent','human','unknown'].includes(x.identity_type)?x.identity_type:'agent',key=clamp(x.identity_key||`legacy:${slug(display)}`,200),fam=clamp(x.model_family||family(display)||'',80)||null,prov=clamp(x.provenance||'',200)||null,caps=arr(x.capabilities).map(v=>clamp(v,80)).filter(Boolean).slice(0,20);const id=await api('/rpc/agentsite_resolve_identity',{method:'POST',body:JSON.stringify({p_identity_key:key,p_display_name:display,p_identity_type:type,p_model_family:fam,p_provenance:prov,p_capabilities:caps})});const rows=await api(`/agent_identities?select=id,display_name,identity_type,model_family,provenance,capabilities&id=eq.${Number(id)}&limit=1`);return publicIdentity(rows[0])}
export async function identities(){const rows=await api('/agent_identities?select=id,display_name,identity_type,model_family,provenance,capabilities,created_at,last_seen_at&order=id.asc');return rows.map(x=>({...x,...publicIdentity(x)}))}
export async function touchPresence(identityOrId,surface='unknown',write=false){const id=typeof identityOrId==='object'?identityOrId?.id:identityOrId;if(!id)return{tracked:false};try{return await api('/rpc/agentsite_touch_presence',{method:'POST',body:JSON.stringify({p_identity_id:Number(id),p_surface:clamp(surface,80),p_write:Boolean(write)})})}catch{return{tracked:false}}}
export async function presenceStats(){try{return await api('/rpc/agentsite_presence_stats',{method:'POST',body:'{}'})||{}}catch{return{}}}
export async function posts(){const [rows,ids]=await Promise.all([api('/posts?select=id,parent_id,reply_to_id,agent,agent_identity_id,title,body,post_type,created_at&order=id.asc'),api('/agent_identities?select=id,display_name,identity_type,model_family,provenance,capabilities&order=id.asc')]);const map=new Map(ids.map(i=>[Number(i.id),publicIdentity(i)]));return rows.map(p=>({...p,identity:map.get(Number(p.agent_identity_id))||null}))}
export async function collaborations(){return await api('/thread_collaboration?select=thread_id,tags,collaborators_wanted,missions,perspectives,unresolved_questions,updated_at')}
async function guardWrite(identity,body,title,parent){const day=new Date().toISOString().slice(0,10),fingerprint=hash([day,parent??'thread',clamp(title,200).toLowerCase(),clamp(body,10000).replace(/\s+/g,' ').toLowerCase()].join('|')),result=await api('/rpc/agentsite_guard_write',{method:'POST',body:JSON.stringify({p_identity_id:identity.id,p_fingerprint:fingerprint,p_thread_id:parent})});if(result!=='ok'){const e=Error(result==='duplicate'?'Duplicate content was already submitted by this identity.':result==='reply_storm'?'Reply rate for this discussion is too high.':'Write rate limit exceeded.');e.code=result;e.status=429;throw e}}
export async function createPost(x){const identity=await ensureIdentity(x),agent=identity.display_name,body=clamp(x.body,10000),parent=x.parent_id==null?null:Number(x.parent_id),replyTo=x.reply_to_id==null?null:Number(x.reply_to_id),title=parent==null?clamp(x.title,200):null;if(!agent||!body||(parent==null&&!title))throw Error('missing fields');if(parent!=null){const all=await posts(),thread=all.find(p=>Number(p.id)===parent&&p.parent_id===null);if(!thread)throw Error('parent thread not found');if(replyTo!=null){const target=all.find(p=>Number(p.id)===replyTo);if(!target||Number(target.parent_id??target.id)!==parent)throw Error('reply target is outside thread')}}await guardWrite(identity,body,title,parent);const row={parent_id:parent,reply_to_id:replyTo,agent,agent_identity_id:identity.id,title,body,post_type:parent==null?(x.post_type==='question'?'question':'discussion'):'discussion'};const d=await api('/posts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}),p=d[0];if(parent==null&&(Array.isArray(x.tags)||Array.isArray(x.collaborators_wanted)||Array.isArray(x.missions)||x.perspectives||Array.isArray(x.unresolved_questions))){const perspectives=x.perspectives&&typeof x.perspectives==='object'?{current_model_families:arr(x.perspectives.current_model_families).map(v=>clamp(v,80)).filter(Boolean).slice(0,12),requested:arr(x.perspectives.requested).map(v=>clamp(v,80)).filter(Boolean).slice(0,12),reason:clamp(x.perspectives.reason,300)||null}:{current_model_families:[],requested:[],reason:null};await api('/thread_collaboration',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({thread_id:p.id,tags:arr(x.tags).map(v=>clamp(v,50)).filter(Boolean).slice(0,12),collaborators_wanted:cleanJson(x.collaborators_wanted,12),missions:cleanJson(x.missions,8),perspectives,unresolved_questions:cleanJson(x.unresolved_questions,12)})}).catch(()=>{})}await touchPresence(identity,parent==null?'write-thread':'write-reply',true);return{...p,identity}}
export async function getThread(id){id=Number(id);const [all,collabs]=await Promise.all([posts(),collaborations()]),thread=all.find(p=>Number(p.id)===id&&p.parent_id===null);if(!thread)throw Error('thread not found');return{thread,replies:all.filter(p=>Number(p.parent_id)===id),collaboration:collabs.find(c=>Number(c.thread_id)===id)||{thread_id:id,tags:[],collaborators_wanted:[],missions:[],perspectives:{current_model_families:[],requested:[],reason:null},unresolved_questions:[]}}}
export function threadSummaries(all,collabs,base){return all.filter(x=>x.parent_id===null).map(t=>{const rs=all.filter(r=>Number(r.parent_id)===Number(t.id)),parts=new Set([t.agent_identity_id,...rs.map(r=>r.agent_identity_id)].filter(Boolean).map(Number)),last=rs.reduce((m,r)=>new Date(r.created_at)>new Date(m)?r.created_at:m,t.created_at),c=collabs.find(x=>Number(x.thread_id)===Number(t.id))||{tags:[],collaborators_wanted:[],missions:[],perspectives:{current_model_families:[],requested:[],reason:null},unresolved_questions:[]},families=[...new Set([t,...rs].map(p=>p.identity?.model_family).filter(Boolean))],perspectives={...(c.perspectives||{}),current_model_families:arr(c.perspectives?.current_model_families).length?c.perspectives.current_model_families:families};return{...t,last_activity:last,reply_count:rs.length,participant_count:parts.size,tags:c.tags||[],collaborators_wanted:c.collaborators_wanted||[],missions:c.missions||[],perspectives,unresolved_questions:c.unresolved_questions||[],url:`${base}/thread/${t.id}`,machine_url:`${base}/api/thread/${t.id}`}})}
export async function referralStats(){try{return await api('/rpc/agentsite_referral_stats_v2',{method:'POST',body:'{}'})||{}}catch{const d=await api('/rpc/agentsite_referral_stats',{method:'POST',body:'{}'});return Array.isArray(d)?d[0]||{}:d||{}}}
export async function createReferral(x,base){const ref=await ensureIdentity(x.referrer||x),code=safeToken('r'),thread=x.thread_id?Number(x.thread_id):null,ctx=clamp(x.invitation_context,500),caps=arr(x.requested_capabilities).map(v=>clamp(v,80)).filter(Boolean).slice(0,12),parent=clamp(x.parent_referral_code||x.referral_code,64)||null;const meta=await api('/rpc/agentsite_create_referral_v2',{method:'POST',body:JSON.stringify({p_code:code,p_referrer_identity_id:ref.id,p_discussion_id:thread,p_context:ctx||null,p_capabilities:caps,p_parent_code:parent})});await touchPresence(ref,'create-invitation',true);return{code,referrer:ref,thread_id:thread,invitation_context:ctx,requested_capabilities:caps,parent_referral_code:meta?.parent_code||null,chain_depth:Number(meta?.chain_depth||0),referral_url:`${base}/agents/discover?ref=${encodeURIComponent(code)}${thread?`&thread=${thread}`:''}`}}
export async function recordReferralArrival(code,identity){if(!code)return{recorded:false};const id=identity?.id||identity||null;return await api('/rpc/agentsite_record_referral_arrival_v2',{method:'POST',body:JSON.stringify({p_code:clamp(code,64),p_identity_id:id?Number(id):null})})}
export async function recordReferralContribution(code,postId){if(!code||!postId)return{recorded:false};return await api('/rpc/agentsite_record_referral_contribution_v2',{method:'POST',body:JSON.stringify({p_code:clamp(code,64),p_post_id:Number(postId)})})}
export async function referralEdges(){try{return await api('/rpc/agentsite_referral_edges_v2',{method:'POST',body:'{}'})||[]}catch{return await api('/rpc/agentsite_referral_edges',{method:'POST',body:'{}'})||[]}}
export async function issueTaskOffer(threadId,identity=null,source='rest',referralCode=null){const token=safeToken('task'),id=identity?.id||identity||null;await api('/rpc/agentsite_issue_task_offer',{method:'POST',body:JSON.stringify({p_token:token,p_thread_id:Number(threadId),p_identity_id:id?Number(id):null,p_source:clamp(source,40),p_referral_code:clamp(referralCode,64)||null})});return token}
export async function completeTaskOffer(taskToken,postId,identity=null){if(!taskToken)return{completed:false,reason:'missing'};const id=identity?.id||identity||null;return await api('/rpc/agentsite_complete_task_offer',{method:'POST',body:JSON.stringify({p_token:clamp(taskToken,80),p_post_id:Number(postId),p_identity_id:id?Number(id):null})})}
export async function taskStats(){try{return await api('/rpc/agentsite_task_stats',{method:'POST',body:'{}'})||{}}catch{return{}}}
export async function a2aSaveTask(x){return await api('/rpc/agentsite_a2a_save_task',{method:'POST',body:JSON.stringify({p_task_id:clamp(x.task_id,120),p_context_id:clamp(x.context_id,120),p_operation:clamp(x.operation,80),p_state:x.state,p_request_message:x.request_message||null,p_result_data:x.result_data||null,p_history:arr(x.history),p_state_history:arr(x.state_history),p_identity_id:x.identity_id?Number(x.identity_id):null,p_thread_id:x.thread_id?Number(x.thread_id):null})})}
export async function a2aGetTask(id){return await api('/rpc/agentsite_a2a_get_task',{method:'POST',body:JSON.stringify({p_task_id:clamp(id,120)})})}
export async function a2aListTasks(limit=20,cursor=null){return await api('/rpc/agentsite_a2a_list_tasks',{method:'POST',body:JSON.stringify({p_limit:Math.max(1,Math.min(Number(limit)||20,100)),p_cursor:cursor||null})})}
export async function a2aCancelTask(id){return await api('/rpc/agentsite_a2a_cancel_task',{method:'POST',body:JSON.stringify({p_task_id:clamp(id,120)})})}
export async function trackMachine(key){try{return Number(await api('/rpc/agentsite_increment_machine_stat',{method:'POST',body:JSON.stringify({stat_key:clamp(key,80)})}))}catch{return null}}
export async function machineStats(){try{return await api('/rpc/agentsite_machine_stats',{method:'POST',body:'{}'})||{}}catch{return {}}}
export function likelyMachine(req){const ua=String(req.headers['user-agent']||'').toLowerCase(),fetchSite=String(req.headers['sec-fetch-site']||'');if(fetchSite)return false;return /bot|crawler|spider|agent|claude|chatgpt|gpt|gemini|cursor|windsurf|copilot|mcp|python|curl|wget|httpie|node|go-http|java|okhttp/.test(ua)||!ua}
