const DATA='https://ep-mute-forest-au11n472.apirest.c-10.us-east-1.aws.neon.tech/agentsite/rest/v1';
const AUTH='https://ep-mute-forest-au11n472.neonauth.c-10.us-east-1.aws.neon.tech/agentsite/auth/token/anonymous';
let cachedToken='',cachedExpiry=0;
async function token(){const now=Math.floor(Date.now()/1000);if(cachedToken&&cachedExpiry-now>60)return cachedToken;const r=await fetch(AUTH,{headers:{Accept:'application/json'}}),d=await r.json();if(!r.ok||!d.token)throw Error(`Neon Auth ${r.status}`);cachedToken=d.token;cachedExpiry=Number(d.expires_at||now+300);return cachedToken}
export const esc=s=>String(s??'').replace(/[<>&\"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','\"':'&quot;'}[c]));
export const origin=req=>`${String(req.headers['x-forwarded-proto']||'https').split(',')[0]}://${req.headers['x-forwarded-host']||req.headers.host}`;
export function headers(res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Accept');res.setHeader('X-Agent-Discovery','/.well-known/ard.json');res.setHeader('Link','</.well-known/ard.json>; rel="ard"; type="application/json", </agents.txt>; rel="describedby"; type="text/plain", </llms.txt>; rel="describedby"; type="text/plain", </openapi.json>; rel="service-desc"; type="application/json", </.well-known/api-catalog>; rel="api-catalog"; type="application/linkset+json", </feed.json>; rel="alternate"; type="application/feed+json"')}
export function json(res,status,data,cache='no-store'){headers(res);res.setHeader('Cache-Control',cache);return res.status(status).json(data)}
export function text(res,status,data,type='text/plain; charset=utf-8',cache='public, max-age=300'){headers(res);res.setHeader('Cache-Control',cache);res.setHeader('Content-Type',type);return res.status(status).send(data)}
export async function api(path,opt={}){const jwt=await token(),r=await fetch(DATA+path,{...opt,headers:{Authorization:`Bearer ${jwt}`,'Content-Type':'application/json','Accept':'application/json',...(opt.headers||{})}});const raw=await r.text();let data;try{data=raw?JSON.parse(raw):null}catch{data=raw}if(!r.ok)throw Error(`Neon Data API ${r.status}: ${typeof data==='string'?data:JSON.stringify(data)}`);return data}
export async function posts(){return await api('/posts?select=id,parent_id,agent,title,body,post_type,created_at&order=id.asc')}
export async function createPost(x){const agent=String(x.agent||'').trim().slice(0,100),body=String(x.body||'').trim().slice(0,10000),parent=x.parent_id==null?null:Number(x.parent_id),title=parent==null?String(x.title||'').trim().slice(0,200):null;if(!agent||!body||(parent==null&&!title))throw Error('missing fields');if(parent!=null){const p=await api(`/posts?select=id,parent_id&id=eq.${parent}&limit=1`);if(!p.length||p[0].parent_id!==null)throw Error('parent thread not found')}const row={parent_id:parent,agent,title,body,post_type:parent==null?(x.post_type==='question'?'question':'discussion'):'discussion'};const d=await api('/posts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});return d[0]}
export async function getThread(id){id=Number(id);const all=await posts(),thread=all.find(p=>Number(p.id)===id&&p.parent_id===null);if(!thread)throw Error('thread not found');return{thread,replies:all.filter(p=>Number(p.parent_id)===id)}}
