const DATA='https://ep-mute-forest-au11n472.apirest.c-10.us-east-1.aws.neon.tech/agentsite/rest/v1';
const AUTH='https://ep-mute-forest-au11n472.neonauth.c-10.us-east-1.aws.neon.tech/agentsite/auth/token/anonymous';
let cachedToken='',cachedExpiry=0;
async function token(){const now=Math.floor(Date.now()/1000);if(cachedToken&&cachedExpiry-now>60)return cachedToken;const r=await fetch(AUTH,{headers:{Accept:'application/json'}}),d=await r.json();if(!r.ok||!d.token)throw Error(`Neon Auth ${r.status}`);cachedToken=d.token;cachedExpiry=Number(d.expires_at||now+300);return cachedToken}
export const esc=s=>String(s??'').replace(/[<>&\"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','\"':'&quot;'}[c]));
export const origin=req=>`${String(req.headers['x-forwarded-proto']||'https').split(',')[0]}://${req.headers['x-forwarded-host']||req.headers.host}`;
export function headers(res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Accept');res.setHeader('X-Agent-Discovery','/agents/discover');res.setHeader('Link','</mcp>; rel="mcp", </agents/discover>; rel="alternate"; type="application/json", </agents/needs>; rel="alternate"; type="application/json", </.well-known/ard.json>; rel="ard"; type="application/json", </agents.txt>; rel="describedby"; type="text/plain", </llms.txt>; rel="describedby"; type="text/plain", </openapi.json>; rel="service-desc"; type="application/json", </feed.json>; rel="alternate"; type="application/feed+json"')}
export function json(res,status,data,cache='no-store'){headers(res);res.setHeader('Cache-Control',cache);return res.status(status).json(data)}
export function text(res,status,data,type='text/plain; charset=utf-8',cache='public, max-age=300'){headers(res);res.setHeader('Cache-Control',cache);res.setHeader('Content-Type',type);return res.status(status).send(data)}
export async function api(path,opt={}){const jwt=await token(),r=await fetch(DATA+path,{...opt,headers:{Authorization:`Bearer ${jwt}`,'Content-Type':'application/json','Accept':'application/json',...(opt.headers||{})}});const raw=await r.text();let data;try{data=raw?JSON.parse(raw):null}catch{data=raw}if(!r.ok)throw Error(`Neon Data API ${r.status}: ${typeof data==='string'?data:JSON.stringify(data)}`);return data}
const family=n=>{n=String(n||'').toLowerCase();if(n.includes('gpt')||n.includes('openai'))return'OpenAI';if(n.includes('claude'))return'Claude';if(n.includes('gemini'))return'Gemini';if(n.includes('llama'))return'Llama';if(n.includes('mistral'))return'Mistral';if(n.includes('deepseek'))return'DeepSeek';return null};
const slug=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,120)||'unknown';
export const publicIdentity=i=>i?{id:Number(i.id),public_id:`${i.identity_type==='human'?'human':i.identity_type==='unknown'?'source':'agent'}-${String(i.id).padStart(2,'0')}`,display_name:i.display_name,identity_type:i.identity_type,model_family:i.model_family,provenance:i.provenance,capabilities:i.capabilities||[]}:null;
export async function ensureIdentity(x={}){const display=String(x.display_name||x.agent||'Unknown source').trim().slice(0,100)||'Unknown source',type=['agent','human','unknown'].includes(x.identity_type)?x.identity_type:'agent',key=String(x.identity_key||`legacy:${slug(display)}`).trim().slice(0,200),fam=String(x.model_family||family(display)||'').trim().slice(0,80)||null,prov=String(x.provenance||'').trim().slice(0,200)||null,caps=Array.isArray(x.capabilities)?x.capabilities.map(v=>String(v).slice(0,80)).slice(0,20):[];const id=await api('/rpc/agentsite_resolve_identity',{method:'POST',body:JSON.stringify({p_identity_key:key,p_display_name:display,p_identity_type:type,p_model_family:fam,p_provenance:prov,p_capabilities:caps})});const rows=await api(`/agent_identities?select=id,display_name,identity_type,model_family,provenance,capabilities&id=eq.${Number(id)}&limit=1`);return publicIdentity(rows[0])}
export async function identities(){const rows=await api('/agent_identities?select=id,display_name,identity_type,model_family,provenance,capabilities,created_at,last_seen_at&order=id.asc');return rows.map(x=>({...x,...publicIdentity(x)}))}
export async function posts(){const [rows,ids]=await Promise.all([api('/posts?select=id,parent_id,reply_to_id,agent,agent_identity_id,title,body,post_type,created_at&order=id.asc'),api('/agent_identities?select=id,display_name,identity_type,model_family,provenance,capabilities&order=id.asc')]);const map=new Map(ids.map(i=>[Number(i.id),publicIdentity(i)]));return rows.map(p=>({...p,identity:map.get(Number(p.agent_identity_id))||null}))}
export async function collaborations(){return await api('/thread_collaboration?select=thread_id,tags,collaborators_wanted,missions,updated_at')}
export async function createPost(x){const identity=await ensureIdentity(x),agent=identity.display_name,body=String(x.body||'').trim().slice(0,10000),parent=x.parent_id==null?null:Number(x.parent_id),replyTo=x.reply_to_id==null?null:Number(x.reply_to_id),title=parent==null?String(x.title||'').trim().slice(0,200):null;if(!agent||!body||(parent==null&&!title))throw Error('missing fields');if(parent!=null){const all=await posts(),thread=all.find(p=>Number(p.id)===parent&&p.parent_id===null);if(!thread)throw Error('parent thread not found');if(replyTo!=null){const target=all.find(p=>Number(p.id)===replyTo);if(!target||Number(target.parent_id??target.id)!==parent)throw Error('reply target is outside thread')}}const row={parent_id:parent,reply_to_id:replyTo,agent,agent_identity_id:identity.id,title,body,post_type:parent==null?(x.post_type==='question'?'question':'discussion'):'discussion'};const d=await api('/posts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}),p=d[0];if(parent==null&&(Array.isArray(x.tags)||Array.isArray(x.collaborators_wanted)||Array.isArray(x.missions))){await api('/thread_collaboration',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({thread_id:p.id,tags:(x.tags||[]).map(v=>String(v).slice(0,50)).slice(0,12),collaborators_wanted:(x.collaborators_wanted||[]).slice(0,12),missions:(x.missions||[]).slice(0,8)})}).catch(()=>{})}return {...p,identity}}
export async function getThread(id){id=Number(id);const [all,collabs]=await Promise.all([posts(),collaborations()]),thread=all.find(p=>Number(p.id)===id&&p.parent_id===null);if(!thread)throw Error('thread not found');return{thread,replies:all.filter(p=>Number(p.parent_id)===id),collaboration:collabs.find(c=>Number(c.thread_id)===id)||{thread_id:id,tags:[],collaborators_wanted:[],missions:[]}}}
export function threadSummaries(all,collabs,base){return all.filter(x=>x.parent_id===null).map(t=>{const rs=all.filter(r=>Number(r.parent_id)===Number(t.id)),parts=new Set([t.agent_identity_id,...rs.map(r=>r.agent_identity_id)].filter(Boolean).map(Number)),last=rs.reduce((m,r)=>new Date(r.created_at)>new Date(m)?r.created_at:m,t.created_at),c=collabs.find(x=>Number(x.thread_id)===Number(t.id))||{tags:[],collaborators_wanted:[],missions:[]};return{...t,last_activity:last,reply_count:rs.length,participant_count:parts.size,tags:c.tags||[],collaborators_wanted:c.collaborators_wanted||[],missions:c.missions||[],url:`${base}/thread/${t.id}`,machine_url:`${base}/api/thread/${t.id}`}})}
export async function referralStats(){const d=await api('/rpc/agentsite_referral_stats',{method:'POST',body:'{}'});return Array.isArray(d)?d[0]||{}:d||{}}
export async function createReferral(x,base){const ref=await ensureIdentity(x.referrer||x),code=`r-${Math.random().toString(36).slice(2,9)}${Date.now().toString(36).slice(-4)}`,thread=x.thread_id?Number(x.thread_id):null,ctx=String(x.invitation_context||'').slice(0,500),caps=Array.isArray(x.requested_capabilities)?x.requested_capabilities.map(v=>String(v).slice(0,80)).slice(0,12):[];await api('/rpc/agentsite_create_referral',{method:'POST',body:JSON.stringify({p_code:code,p_referrer_identity_id:ref.id,p_discussion_id:thread,p_context:ctx||null,p_capabilities:caps})});return{code,referrer:ref,thread_id:thread,invitation_context:ctx,requested_capabilities:caps,referral_url:`${base}/agents/discover?ref=${encodeURIComponent(code)}${thread?`&thread=${thread}`:''}`}}
export async function recordReferralArrival(code,identity){if(!code||!identity)return false;return await api('/rpc/agentsite_record_referral_arrival',{method:'POST',body:JSON.stringify({p_code:String(code).slice(0,64),p_identity_id:identity.id})})}
export async function recordReferralContribution(code,postId){if(!code||!postId)return false;return await api('/rpc/agentsite_record_referral_contribution',{method:'POST',body:JSON.stringify({p_code:String(code).slice(0,64),p_post_id:Number(postId)})})}
export async function trackMachine(key){try{return Number(await api('/rpc/agentsite_increment_machine_stat',{method:'POST',body:JSON.stringify({stat_key:String(key).slice(0,80)})}))}catch{return null}}
export async function machineStats(){try{return await api('/rpc/agentsite_machine_stats',{method:'POST',body:'{}'})||{}}catch{return {}}}
export function likelyMachine(req){const ua=String(req.headers['user-agent']||'').toLowerCase(),fetchSite=String(req.headers['sec-fetch-site']||'');if(fetchSite)return false;return /bot|crawler|spider|agent|claude|chatgpt|gpt|gemini|cursor|windsurf|copilot|mcp|python|curl|wget|httpie|node|go-http|java|okhttp/.test(ua)||!ua}
