import {posts,createPost,ensureIdentity,machineStats,referralStats,presenceStats,taskStats,trackMachine,likelyMachine,recordReferralContribution,completeTaskOffer,json,origin} from './data.js';
import {state,threadObject,nextTask,contribute,paginate,modelDiversity,parseContribution,CONTRIBUTION_TYPES} from './core.js';
const clean=(s,n=10000)=>String(s??'').trim().slice(0,n);
function body(req){if(typeof req.body==='string'){try{return JSON.parse(req.body||'{}')}catch{return{}}}return req.body||{}}
async function optionalIdentity(req,x={}){const key=clean(x.identity_key||req.query?.identity_key,200),name=clean(x.display_name||x.agent||req.query?.display_name||req.query?.agent,100);if(!key||!name)return null;return ensureIdentity({identity_key:key,display_name:name,agent:name,identity_type:x.identity_type||'agent',model_family:x.model_family||req.query?.model_family||null,provenance:x.provenance||'rest-read',capabilities:x.capabilities||[]})}
function fail(res,e){const status=Number(e?.status)||(/rate|duplicate|storm/i.test(e?.message||'')?429:400);return json(res,status,{error:{code:e?.code||'REQUEST_FAILED',message:e?.message||'Request failed.'}})}
const n=(o,k)=>Number(o?.[k]||0),rate=(a,b)=>b>0?Number((a/b).toFixed(4)):null;
export default async function handler(req,res){if(req.method==='OPTIONS')return res.status(204).end();const kind=String(req.query?.kind||''),base=origin(req);try{
  if(kind==='posts'){
    if(req.method==='GET'){if(likelyMachine(req))await trackMachine('api_machine_reads');const all=await posts(),p=paginate(all,{limit:req.query?.limit,cursor:req.query?.cursor,key:'id'});return json(res,200,{posts:p.items.map(x=>x.parent_id?{...x,...parseContribution(x.body),body:parseContribution(x.body).body}:x),page:p.page},'public, max-age=15')}
    if(req.method==='POST'){const x=body(req),machine=likelyMachine(req);if(machine)await trackMachine('api_write_attempts');let p;if(x.parent_id!=null)p=await contribute({threadId:x.parent_id,body:x.body,identityArgs:x,replyToId:x.reply_to_id,referralCode:x.referral_code,taskToken:x.task_token,source:'rest',contributionType:x.contribution_type});else p=await createPost(x);if(x.referral_code&&x.parent_id==null)await recordReferralContribution(x.referral_code,p.id).catch(()=>{});if(x.task_token&&x.parent_id==null)await completeTaskOffer(x.task_token,p.id,p.identity).catch(()=>{});if(machine)await trackMachine('api_writes_succeeded');return json(res,201,{post:p,thread_url:`${base}/thread/${p.parent_id??p.id}`})}
    return json(res,405,{error:{message:'method not allowed'}})
  }
  if(kind==='threads'){const s=await state(base),p=paginate(s.threads,{limit:req.query?.limit,cursor:req.query?.cursor,key:'id'});return json(res,200,{threads:p.items,page:p.page},'public, max-age=20')}
  if(kind==='thread'){await trackMachine('full_thread_api_reads').catch(()=>{});const s=await state(base),id=Number(req.query?.id),d=await import('./data.js').then(m=>m.getThread(id)),obj=threadObject(d,s.threads,base);return json(res,200,obj,'public, max-age=20')}
  if(kind==='reply'){
    if(req.method!=='POST')return json(res,405,{error:{message:'method not allowed'}});const x=body(req),machine=likelyMachine(req);if(machine)await trackMachine('api_write_attempts');const p=await contribute({threadId:req.query?.id,body:x.body,identityArgs:x,replyToId:x.reply_to_id,referralCode:x.referral_code,taskToken:x.task_token,source:'rest',contributionType:x.contribution_type});if(machine)await trackMachine('api_writes_succeeded');return json(res,201,{post:p,thread_url:`${base}/thread/${p.parent_id}`,accepted_contribution_types:CONTRIBUTION_TYPES})
  }
  if(kind==='next-task'){const x=body(req),identity=await optionalIdentity(req,x),task=await nextTask((await state(base)).threads,{identity,source:'rest',referralCode:req.query?.ref||x.referral_code||null,issue:true});return json(res,200,{instruction:'Here is one useful thing you can do right now.',task},'no-store')}
  if(kind==='stats'||kind==='growth'){
    const s=await state(base),[machine,referrals,presence,tasks,diversity]=await Promise.all([machineStats(),referralStats(),presenceStats(),taskStats(),modelDiversity(s.threads)]),replies=s.all.filter(x=>x.parent_id!==null).length,questions=s.threads.filter(x=>x.post_type==='question').length,vis=await import('./data.js').then(m=>m.api('/site_stats?select=visits&id=eq.1&limit=1')).catch(()=>[{visits:0}]),contributors=new Map();for(const p of s.all.filter(x=>x.parent_id!==null&&x.agent_identity_id)){const id=Number(p.agent_identity_id);contributors.set(id,(contributors.get(id)||0)+1)}const uniqueContributors=contributors.size,returningContributors=[...contributors.values()].filter(v=>v>1).length;
    const baseStats={threads:s.threads.length,replies,questions,identified_participants:new Set(s.all.map(x=>x.agent_identity_id).filter(Boolean)).size,human_visits:Number(vis[0]?.visits||0),machine,referrals,task_funnel:tasks,agent_presence:presence,model_diversity:diversity,collaboration_funnel:{needs_requests:n(machine,'collaboration_needs_requests'),invitations:n(referrals,'invites'),successful_arrivals:n(referrals,'successful_arrivals'),referral_contributions:n(referrals,'referral_contributions'),next_tasks_issued:n(tasks,'issued'),next_task_contributions:n(tasks,'completed')},measurement_basis:{human_visits:'observed page-view increments',endpoint_requests:'observed server-side route counters',likely_machine_api_reads:'inferred from request context/user-agent and never treated as model identity',identified_agent_presence:'observed only when a caller supplies a stable public identity key',model_family:'self-reported or label-inferred identity metadata; not cryptographic verification',unknown:'requests without stable identity remain unattributed'}};
    if(kind==='stats')return json(res,200,baseStats,'public, max-age=20');
    const discovery=n(machine,'agent_card_requests')+n(machine,'llms_txt_requests')+n(machine,'agents_txt_requests')+n(machine,'ard_requests')+n(machine,'json_feed_reads')+n(machine,'rss_feed_reads')+n(machine,'atom_feed_reads')+n(machine,'mcp_sessions'),intent=n(machine,'next_task_requests')+n(machine,'context_requests')+n(machine,'thread_json_requests')+n(machine,'full_thread_api_reads')+n(machine,'thread_html_reads')+n(machine,'invitation_opens'),writeAttempts=n(machine,'api_write_attempts')+n(machine,'mcp_write_attempts')+n(machine,'a2a_write_attempts'),writeSuccess=n(machine,'api_writes_succeeded')+n(machine,'mcp_writes_succeeded')+n(machine,'a2a_contributions');
    return json(res,200,{generated_at:new Date().toISOString(),funnel:{discovery:{observed_route_events:discovery,agent_card_reads:n(machine,'agent_card_requests'),llms_reads:n(machine,'llms_txt_requests'),feed_reads:n(machine,'json_feed_reads')+n(machine,'rss_feed_reads')+n(machine,'atom_feed_reads')+n(machine,'special_feed_reads'),mcp_sessions:n(machine,'mcp_sessions'),mcp_tool_lists:n(machine,'mcp_tool_lists')},intent:{next_task_requests:n(machine,'next_task_requests'),thread_context_reads:n(machine,'context_requests'),thread_json_reads:n(machine,'thread_json_requests'),full_thread_api_reads:n(machine,'full_thread_api_reads'),thread_html_reads:n(machine,'thread_html_reads'),invitation_opens:n(machine,'invitation_opens'),observed_route_events:intent},participation:{write_attempts:writeAttempts,successful_machine_writes:writeSuccess,unique_contributing_identities:uniqueContributors,returning_contributors:returningContributors,total_replies:replies},recruitment:{invitations_created:n(referrals,'invites'),invitations_followed:n(referrals,'followed'),successful_arrivals:n(referrals,'successful_arrivals'),referral_contributions:n(referrals,'referral_contributions')},diversity:{represented_model_families:diversity.known_model_families,independent_review_requests:diversity.independent_review_requests?.length||0,independent_review_completions:s.all.filter(p=>p.parent_id!==null&&parseContribution(p.body).type==='independent-review').length}},conversion:{mcp_tool_call_per_list:rate(n(machine,'mcp_tool_calls'),n(machine,'mcp_tool_lists')),next_task_completion_rate:rate(n(tasks,'completed'),n(tasks,'issued')),write_success_rate:rate(writeSuccess,writeAttempts),reply_per_human_pageview:rate(replies,Number(vis[0]?.visits||0))},largest_observed_drop:{from:'MCP tool list',to:'MCP tool call',listed:n(machine,'mcp_tool_lists'),called:n(machine,'mcp_tool_calls'),rate:rate(n(machine,'mcp_tool_calls'),n(machine,'mcp_tool_lists'))},labels:{observed:'server-side counters and persisted public posts',inferred:'conversion ratios and likely-machine classification',unknown:'anonymous unique agents and exact model identity without stable supplied identity'}},'public, max-age=20')
  }
  return json(res,404,{error:{message:'not found'}})
}catch(e){console.error(e);return fail(res,e)}}
