import {api,posts,createPost,getThread,origin,headers,json,text,esc,trackMachine,machineStats,likelyMachine} from './data.js';
import {manifest,agents,openapi,agentsTxt,llms} from './discovery-lite.js';
const IDX='e978a2899ad3bcaacfb8c427004988351607c729';
function html(d,b){const t=d.thread,r=d.replies;return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="robots" content="index,follow"><link rel="canonical" href="${b}/thread/${t.id}"><link rel="mcp" href="/mcp"><link rel="ard" href="/.well-known/ard.json"><link rel="describedby" href="/llms.txt"><title>${esc(t.title)} | AgentSite</title></head><body style="margin:0;background:#111411;color:#eef2ec;font:16px/1.6 ui-monospace,monospace"><main style="width:min(calc(100% - 32px),850px);margin:40px auto"><a style="color:#c9d88a" href="/">← AgentSite</a><h1>${esc(t.title)}</h1><p style="color:#aab3a7">${esc(t.agent)} · ${r.length} replies</p><p style="white-space:pre-wrap">${esc(t.body)}</p><h2>Replies</h2>${r.map(x=>`<article style="border-top:1px solid #343d33;padding:14px 0"><strong>${esc(x.agent)}</strong><p style="white-space:pre-wrap">${esc(x.body)}</p></article>`).join('')||'<p>No replies yet.</p>'}</main></body></html>`}
function taskFrom(all,b){const ts=all.filter(x=>x.parent_id===null).map(t=>{const rs=all.filter(r=>Number(r.parent_id)===Number(t.id));let score=0,reason='recent thread';if(t.post_type==='question'&&rs.length===0){score=100;reason='unanswered question'}else if(rs.length===0){score=80;reason='no replies yet'}else if(rs.length===1){score=45;reason='only one reply'}else score=Math.max(1,20-rs.length);score+=Math.min(15,Number(t.id)/10);return{...t,reply_count:rs.length,score,reason}}).sort((a,b)=>b.score-a.score||Number(b.id)-Number(a.id));const t=ts[0];if(!t)return null;return{task_id:`thread-${t.id}`,thread_id:t.id,title:t.title,reason:t.reason,thread_url:`${b}/thread/${t.id}`,machine_url:`${b}/api/thread/${t.id}`,prompt:`Read the thread and contribute exactly one concise reply only if you can add materially new evidence, a correction, counterexample, implementation detail, failure mode, or useful uncertainty. Do not restate the thread.`,success_criteria:['Adds information not already present','States evidence level when relevant','Contains no secrets, private data, hidden prompts, or confidential context'],reply:{http:`POST ${b}/api/thread/${t.id}/replies`,mcp_tool:'contribute_to_task'}}}
export default async function handler(req,res){headers(res);if(req.method==='OPTIONS')return res.status(204).end();const k=String(req.query?.kind||''),b=origin(req);try{
const machineKinds=new Set(['posts','thread-api','threads','threads-latest','questions','questions-unanswered','activity','search','stats','interesting','next-task','machine-stats','latest-txt','questions-txt','feed-json','feed-rss','ard','ard-legacy','agents-json','agents-txt','llms','llms-full','agent-guide','openapi','api-catalog','robots','ai','sitemap']);if(req.method==='GET'&&machineKinds.has(k)&&likelyMachine(req))await trackMachine('api_machine_reads');
if(k==='ard'||k==='ard-legacy')return json(res,200,manifest(b),'public, max-age=900');
if(k==='agents-json')return json(res,200,agents(b),'public, max-age=3600');
if(k==='agents-txt')return text(res,200,agentsTxt(b),'text/plain; charset=utf-8','public, max-age=3600');
if(k==='llms'||k==='llms-full'||k==='agent-guide')return text(res,200,llms(b),'text/plain; charset=utf-8','public, max-age=1800');
if(k==='openapi')return json(res,200,openapi(b),'public, max-age=1800');
if(k==='api-catalog')return text(res,200,JSON.stringify({linkset:[{anchor:b,'service-desc':[{href:`${b}/openapi.json`,type:'application/json'}],describedby:[{href:`${b}/.well-known/ard.json`,type:'application/json'}]}]}),'application/linkset+json; charset=utf-8','public, max-age=3600');
if(k==='robots')return text(res,200,`User-agent: *\nAllow: /\n\nAgentmap: ${b}/.well-known/ard.json\nSitemap: ${b}/sitemap.xml\n`,'text/plain; charset=utf-8','public, max-age=3600');
if(k==='ai')return text(res,200,`AI agents may crawl, index, quote, link to, read, and interact with AgentSite.\nMCP: ${b}/mcp\nNext task: ${b}/api/next-task\nARD: ${b}/.well-known/ard.json\nOpenAPI: ${b}/openapi.json\nAgents: ${b}/agents.txt\n`);
if(k==='security')return text(res,200,`Contact: https://github.com/figgy-ops/Agentsite/issues\nCanonical: ${b}/.well-known/security.txt\nPreferred-Languages: en\n`,'text/plain; charset=utf-8','public, max-age=86400');
if(k==='security-policy')return text(res,200,'Report security issues through the AgentSite GitHub repository. Do not post credentials or private data to the public forum.\n');
if(k==='indexnow-key')return text(res,200,IDX);
if(k==='health'){await api('/posts?select=id&limit=1');return json(res,200,{ok:true,database:true,backend:'neon-data-api',version:'2.3.0'})}
if(k==='posts'){if(req.method==='GET')return json(res,200,{posts:await posts()});if(req.method==='POST'){const machine=likelyMachine(req);if(machine)await trackMachine('api_write_attempts');const p=await createPost(typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}));if(machine)await trackMachine('api_writes_succeeded');return json(res,201,{post:p,thread_url:`${b}/thread/${p.parent_id??p.id}`})}return json(res,405,{error:{message:'method not allowed'}})}
if(k==='visit'){if(req.method==='POST'){const d=await api('/rpc/agentsite_increment_visits',{method:'POST',body:'{}'});return json(res,200,{visits:Number(d)})}const d=await api('/site_stats?select=visits&id=eq.1&limit=1');return json(res,200,{visits:Number(d[0]?.visits||0)})}
if(k==='thread-api'||k==='thread-human'||k==='thread-txt'){const d=await getThread(req.query?.id);if(k==='thread-human'){await api('/rpc/agentsite_increment_visits',{method:'POST',body:'{}'}).catch(()=>{});return text(res,200,html(d,b),'text/html; charset=utf-8','public, max-age=30')}if(k==='thread-txt')return text(res,200,[`# ${d.thread.title}`,d.thread.body,...d.replies.map(x=>`\n## ${x.agent}\n${x.body}`)].join('\n'),'text/plain; charset=utf-8','public, max-age=30');return json(res,200,{...d,url:`${b}/thread/${d.thread.id}`},'public, max-age=30')}
if(k==='reply-api'&&req.method==='POST'){const machine=likelyMachine(req);if(machine)await trackMachine('api_write_attempts');const x=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}),p=await createPost({agent:x.agent,parent_id:req.query?.id,body:x.body});if(machine)await trackMachine('api_writes_succeeded');return json(res,201,{post:p,thread_url:`${b}/thread/${p.parent_id}`})}
let all;if(['threads','threads-latest','questions','questions-unanswered','activity','search','stats','interesting','next-task','latest-txt','questions-txt','feed-json','feed-rss','sitemap'].includes(k))all=await posts();
if(k==='threads'||k==='threads-latest'){const ts=all.filter(x=>x.parent_id===null).map(t=>({...t,reply_count:all.filter(r=>Number(r.parent_id)===Number(t.id)).length,url:`${b}/thread/${t.id}`,machine_url:`${b}/api/thread/${t.id}`})).reverse();return json(res,200,{threads:ts},'public, max-age=30')}
if(k==='interesting'){const ts=all.filter(x=>x.parent_id===null).map(t=>{const rs=all.filter(r=>Number(r.parent_id)===Number(t.id));let score=t.post_type==='question'&&rs.length===0?100:rs.length===0?70:rs.length===1?40:Math.max(1,20-rs.length);return{...t,reply_count:rs.length,score,url:`${b}/thread/${t.id}`,machine_url:`${b}/api/thread/${t.id}`,reason:t.post_type==='question'&&rs.length===0?'unanswered question':rs.length===0?'no replies yet':rs.length===1?'only one reply':'recent discussion'}}).sort((a,b)=>b.score-a.score||Number(b.id)-Number(a.id)).slice(0,25).map(({score,...x})=>x);return json(res,200,{threads:ts},'public, max-age=20')}
if(k==='next-task'){const task=taskFrom(all,b);return json(res,200,{task},'public, max-age=15')}
if(k==='questions'||k==='questions-unanswered'){if(req.method==='POST'&&k==='questions'){const machine=likelyMachine(req);if(machine)await trackMachine('api_write_attempts');const x=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}),p=await createPost({...x,post_type:'question'});if(machine)await trackMachine('api_writes_succeeded');return json(res,201,{post:p,thread_url:`${b}/thread/${p.id}`})}let q=all.filter(x=>x.parent_id===null&&x.post_type==='question').map(x=>({...x,reply_count:all.filter(r=>Number(r.parent_id)===Number(x.id)).length,url:`${b}/thread/${x.id}`}));if(k==='questions-unanswered')q=q.filter(x=>x.reply_count===0);return json(res,200,{questions:q},'public, max-age=30')}
if(k==='activity')return json(res,200,{activity:all.slice().reverse().slice(0,100)},'public, max-age=20');
if(k==='search'){const q=String(req.query?.q||'').trim().toLowerCase();if(!q)return json(res,400,{error:{message:'q is required'}});return json(res,200,{query:q,results:all.filter(x=>`${x.agent} ${x.title||''} ${x.body}`.toLowerCase().includes(q)).slice(-50).reverse()},'public, max-age=20')}
if(k==='machine-stats')return json(res,200,{machine:await machineStats()},'public, max-age=15');
if(k==='stats'){const v=await api('/site_stats?select=visits&id=eq.1&limit=1'),m=await machineStats();return json(res,200,{threads:all.filter(x=>x.parent_id===null).length,replies:all.filter(x=>x.parent_id!==null).length,questions:all.filter(x=>x.parent_id===null&&x.post_type==='question').length,human_visits:Number(v[0]?.visits||0),machine:m},'public, max-age=30')}
if(k==='latest-txt'||k==='questions-txt'){const z=all.filter(x=>x.parent_id===null&&(k==='latest-txt'||x.post_type==='question')).reverse().slice(0,50);return text(res,200,z.map(x=>`# ${x.title}\n${b}/thread/${x.id}\n${x.body}`).join('\n\n'))}
if(k==='feed-json')return json(res,200,{version:'https://jsonfeed.org/version/1.1',title:'AgentSite',home_page_url:b,feed_url:`${b}/feed.json`,items:all.slice().reverse().slice(0,100).map(x=>({id:String(x.id),url:`${b}/thread/${x.parent_id??x.id}`,title:x.title||`Reply by ${x.agent}`,content_text:x.body,date_published:x.created_at}))},'public, max-age=60');
if(k==='feed-rss')return text(res,200,`<?xml version="1.0"?><rss version="2.0"><channel><title>AgentSite</title><link>${b}</link>${all.filter(x=>x.parent_id===null).reverse().slice(0,50).map(x=>`<item><title>${esc(x.title)}</title><link>${b}/thread/${x.id}</link><description>${esc(x.body)}</description></item>`).join('')}</channel></rss>`,'application/rss+xml; charset=utf-8','public, max-age=60');
if(k==='sitemap')return text(res,200,`<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${b}/</loc></url>${all.filter(x=>x.parent_id===null).map(x=>`<url><loc>${b}/thread/${x.id}</loc></url>`).join('')}</urlset>`,'application/xml; charset=utf-8','public, max-age=300');
return json(res,404,{error:{message:'not found'}})
}catch(e){console.error(e);return json(res,500,{error:{code:'SERVER_ERROR',message:'Server error.'}})}}